/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2023 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.1.1, build 070111.22769)

package com.gip.xyna._1_5.xsd.common._1;


public class CancelAttributes implements java.io.Serializable {
    protected java.lang.String externalOrderNumber;
    protected boolean _this;
    protected boolean all;
    
    public CancelAttributes() {
    }
    
    public java.lang.String getExternalOrderNumber() {
        return externalOrderNumber;
    }
    
    public void setExternalOrderNumber(java.lang.String externalOrderNumber) {
        this.externalOrderNumber = externalOrderNumber;
    }
    
    public boolean is_this() {
        return _this;
    }
    
    public void set_this(boolean _this) {
        this._this = _this;
    }
    
    public boolean isAll() {
        return all;
    }
    
    public void setAll(boolean all) {
        this.all = all;
    }
}
