/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2023 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.2.0, build 070214.46086)

package com.gip.xyna._1_5.xsd.common._1;


public class XynaStatus_ctype implements java.io.Serializable {
    protected java.lang.String status;
    protected java.lang.String statusReferenceNumber;
    protected java.lang.String information;
    
    public XynaStatus_ctype() {
    }
    
    public java.lang.String getStatus() {
        return status;
    }
    
    public void setStatus(java.lang.String status) {
        this.status = status;
    }
    
    public java.lang.String getStatusReferenceNumber() {
        return statusReferenceNumber;
    }
    
    public void setStatusReferenceNumber(java.lang.String statusReferenceNumber) {
        this.statusReferenceNumber = statusReferenceNumber;
    }
    
    public java.lang.String getInformation() {
        return information;
    }
    
    public void setInformation(java.lang.String information) {
        this.information = information;
    }
}
