/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.2.0, build 070214.46086)

package com.gip.xyna._1_5.xsd.common._1;


public class XynaHeader_ctype implements java.io.Serializable {
    protected java.lang.String orderNumber;
    protected java.lang.String orderType;
    protected java.lang.String orderTypeVersion;
    protected java.lang.String department;
    protected java.lang.String creationDate;
    protected java.lang.String startTime;
    protected java.lang.String startTimeSlot;
    protected java.lang.String information;
    protected java.lang.String processId;
    protected java.lang.String reference;
    protected java.lang.String source;
    protected java.lang.String priority;
    protected java.lang.String dependence;
    protected java.lang.String status;
    
    public XynaHeader_ctype() {
    }
    
    public java.lang.String getOrderNumber() {
        return orderNumber;
    }
    
    public void setOrderNumber(java.lang.String orderNumber) {
        this.orderNumber = orderNumber;
    }
    
    public java.lang.String getOrderType() {
        return orderType;
    }
    
    public void setOrderType(java.lang.String orderType) {
        this.orderType = orderType;
    }
    
    public java.lang.String getOrderTypeVersion() {
        return orderTypeVersion;
    }
    
    public void setOrderTypeVersion(java.lang.String orderTypeVersion) {
        this.orderTypeVersion = orderTypeVersion;
    }
    
    public java.lang.String getDepartment() {
        return department;
    }
    
    public void setDepartment(java.lang.String department) {
        this.department = department;
    }
    
    public java.lang.String getCreationDate() {
        return creationDate;
    }
    
    public void setCreationDate(java.lang.String creationDate) {
        this.creationDate = creationDate;
    }
    
    public java.lang.String getStartTime() {
        return startTime;
    }
    
    public void setStartTime(java.lang.String startTime) {
        this.startTime = startTime;
    }
    
    public java.lang.String getStartTimeSlot() {
        return startTimeSlot;
    }
    
    public void setStartTimeSlot(java.lang.String startTimeSlot) {
        this.startTimeSlot = startTimeSlot;
    }
    
    public java.lang.String getInformation() {
        return information;
    }
    
    public void setInformation(java.lang.String information) {
        this.information = information;
    }
    
    public java.lang.String getProcessId() {
        return processId;
    }
    
    public void setProcessId(java.lang.String processId) {
        this.processId = processId;
    }
    
    public java.lang.String getReference() {
        return reference;
    }
    
    public void setReference(java.lang.String reference) {
        this.reference = reference;
    }
    
    public java.lang.String getSource() {
        return source;
    }
    
    public void setSource(java.lang.String source) {
        this.source = source;
    }
    
    public java.lang.String getPriority() {
        return priority;
    }
    
    public void setPriority(java.lang.String priority) {
        this.priority = priority;
    }
    
    public java.lang.String getDependence() {
        return dependence;
    }
    
    public void setDependence(java.lang.String dependence) {
        this.dependence = dependence;
    }
    
    public java.lang.String getStatus() {
        return status;
    }
    
    public void setStatus(java.lang.String status) {
        this.status = status;
    }
}
