/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 GIP SmartMercial GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.2.0, build 070214.46086)

package com.gip.xyna._1_5.xsd.common._1;


public class XynaID_ctype implements java.io.Serializable {
    protected java.lang.String ID0;
    protected java.lang.String ID1;
    protected java.lang.String ID2;
    
    public XynaID_ctype() {
    }
    
    public java.lang.String getID0() {
        return ID0;
    }
    
    public void setID0(java.lang.String ID0) {
        this.ID0 = ID0;
    }
    
    public java.lang.String getID1() {
        return ID1;
    }
    
    public void setID1(java.lang.String ID1) {
        this.ID1 = ID1;
    }
    
    public java.lang.String getID2() {
        return ID2;
    }
    
    public void setID2(java.lang.String ID2) {
        this.ID2 = ID2;
    }
}
