/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.2.0, build 070214.46086)

package com.gip.xyna._1_5.xsd.common._1;


public class XynaOrderReference_ctype implements java.io.Serializable {
    protected java.lang.String orderID;
    protected java.lang.String priority;
    protected java.lang.String capacities;
    protected java.lang.String resources;
    
    public XynaOrderReference_ctype() {
    }
    
    public java.lang.String getOrderID() {
        return orderID;
    }
    
    public void setOrderID(java.lang.String orderID) {
        this.orderID = orderID;
    }
    
    public java.lang.String getPriority() {
        return priority;
    }
    
    public void setPriority(java.lang.String priority) {
        this.priority = priority;
    }
    
    public java.lang.String getCapacities() {
        return capacities;
    }
    
    public void setCapacities(java.lang.String capacities) {
        this.capacities = capacities;
    }
    
    public java.lang.String getResources() {
        return resources;
    }
    
    public void setResources(java.lang.String resources) {
        this.resources = resources;
    }
}
