/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.1.1, build 070111.22769)

package com.gip.xyna._1_5.xsd.common._1;

import javax.xml.soap.SOAPElement;

public class XynaOrder_ctype implements java.io.Serializable {
    protected com.gip.xyna._1_5.xsd.common._1.XynaHeader_ctype xynaHeader;
    protected com.gip.xyna._1_5.scheduler._1.PreSchedulerInformation preSchedulerInformation;
    protected com.gip.xyna._1_5.xsd.common._1.XynaStatus_ctype xynaStatus;
    protected com.gip.xyna._1_5.xsd.common._1.CancelOrder cancelOrder;
    protected com.gip.xyna._1_5.xsd.common._1.ResumeOrder resumeOrder;
    protected com.gip.xyna._1_5.xsd.common._1.SuspendOrder suspendOrder;
    protected com.gip.xyna._1_5.xsd.faults._1.XynaFault_ctype xynaFault;
    
    public XynaOrder_ctype() {
    }
  //folgende beide methoden werden benötigt, damit webservice dispatchermanager kompiliert
  //(da werden intern serializer-klassen gebaut, die XynaOrder_ctype beinhalten, obwohl es
  //im ws nicht benötigt wird)

  public void set_any(SOAPElement s) {
  }

  public SOAPElement get_any() {
    return null;
  }

    public com.gip.xyna._1_5.xsd.common._1.XynaHeader_ctype getXynaHeader() {
        return xynaHeader;
    }
    
    public void setXynaHeader(com.gip.xyna._1_5.xsd.common._1.XynaHeader_ctype xynaHeader) {
        this.xynaHeader = xynaHeader;
    }
    
    public com.gip.xyna._1_5.scheduler._1.PreSchedulerInformation getPreSchedulerInformation() {
        return preSchedulerInformation;
    }
    
    public void setPreSchedulerInformation(com.gip.xyna._1_5.scheduler._1.PreSchedulerInformation preSchedulerInformation) {
        this.preSchedulerInformation = preSchedulerInformation;
    }
    
    public com.gip.xyna._1_5.xsd.common._1.XynaStatus_ctype getXynaStatus() {
        return xynaStatus;
    }
    
    public void setXynaStatus(com.gip.xyna._1_5.xsd.common._1.XynaStatus_ctype xynaStatus) {
        this.xynaStatus = xynaStatus;
    }
    
    public com.gip.xyna._1_5.xsd.common._1.CancelOrder getCancelOrder() {
        return cancelOrder;
    }
    
    public void setCancelOrder(com.gip.xyna._1_5.xsd.common._1.CancelOrder cancelOrder) {
        this.cancelOrder = cancelOrder;
    }
    
    public com.gip.xyna._1_5.xsd.common._1.ResumeOrder getResumeOrder() {
        return resumeOrder;
    }
    
    public void setResumeOrder(com.gip.xyna._1_5.xsd.common._1.ResumeOrder resumeOrder) {
        this.resumeOrder = resumeOrder;
    }
    
    public com.gip.xyna._1_5.xsd.common._1.SuspendOrder getSuspendOrder() {
        return suspendOrder;
    }
    
    public void setSuspendOrder(com.gip.xyna._1_5.xsd.common._1.SuspendOrder suspendOrder) {
        this.suspendOrder = suspendOrder;
    }
    
    public com.gip.xyna._1_5.xsd.faults._1.XynaFault_ctype getXynaFault() {
        return xynaFault;
    }
    
    public void setXynaFault(com.gip.xyna._1_5.xsd.faults._1.XynaFault_ctype xynaFault) {
        this.xynaFault = xynaFault;
    }
}
