/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 GIP SmartMercial GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.xact.triggerv6.dhcp;

import com.gip.xyna.utils.exceptions.ExceptionStorage;
import java.util.List;
import com.gip.xyna.utils.exceptions.XynaException;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2011-03-25T09:01:38Z;
public class DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS extends XynaException {

  static {
    {
      ExceptionStorage.loadFromResource("Exceptions.xml", DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS.class.getClassLoader());
    }
  }

  private String parameterDescriptions;

  public DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS(String parameterDescriptions) {
    super(new String[]{"XYNA-09620", parameterDescriptions + ""});
    setParameterDescriptions(parameterDescriptions);
  }

  public DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS(String parameterDescriptions, Throwable cause) {
    super(new String[]{"XYNA-09620", parameterDescriptions + ""}, cause);
    setParameterDescriptions(parameterDescriptions);
  }

  protected DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS(String[] args) {
    super(args);
  }

  protected DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setParameterDescriptions(String parameterDescriptions) {
    this.parameterDescriptions = parameterDescriptions;
  }

  public String getParameterDescriptions() {
    return parameterDescriptions;
  }

  public DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS initCause(Throwable t) {
    return (DHCPTRIGGER_DHCP_INVALID_STARTPARAMETERS) super.initCause(t);
  }


}
