/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.xact.triggerv6.dhcp;

import com.gip.xyna.utils.exceptions.ExceptionStorage;
import java.util.List;
import com.gip.xyna.utils.exceptions.XynaException;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2011-03-25T09:01:38Z;
public class DHCPTRIGGER_ERROR_STOPPING_TRIGGER extends XynaException {

  static {
    {
      ExceptionStorage.loadFromResource("Exceptions.xml", DHCPTRIGGER_ERROR_STOPPING_TRIGGER.class.getClassLoader());
    }
  }

  private int port;
  private String errorMsg;

  public DHCPTRIGGER_ERROR_STOPPING_TRIGGER(int port, String errorMsg) {
    super(new String[]{"XYNA-09605", port + "", errorMsg + ""});
    setPort(port);
    setErrorMsg(errorMsg);
  }

  public DHCPTRIGGER_ERROR_STOPPING_TRIGGER(int port, String errorMsg, Throwable cause) {
    super(new String[]{"XYNA-09605", port + "", errorMsg + ""}, cause);
    setPort(port);
    setErrorMsg(errorMsg);
  }

  protected DHCPTRIGGER_ERROR_STOPPING_TRIGGER(String[] args) {
    super(args);
  }

  protected DHCPTRIGGER_ERROR_STOPPING_TRIGGER(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setPort(int port) {
    this.port = port;
  }

  public int getPort() {
    return port;
  }

  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }

  public String getErrorMsg() {
    return errorMsg;
  }

  public DHCPTRIGGER_ERROR_STOPPING_TRIGGER initCause(Throwable t) {
    return (DHCPTRIGGER_ERROR_STOPPING_TRIGGER) super.initCause(t);
  }


}
