/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.xact.triggerv6.dhcp;

import com.gip.xyna.utils.exceptions.ExceptionStorage;
import com.gip.xyna.xact.exceptions.XACT_TriggerCouldNotBeStartedException;
import java.util.List;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2011-03-25T09:01:38Z;
public class DHCPTRIGGER_PORT_ALREADY_IN_USE extends XACT_TriggerCouldNotBeStartedException {

  static {
    {
      ExceptionStorage.loadFromResource("Exceptions.xml", DHCPTRIGGER_PORT_ALREADY_IN_USE.class.getClassLoader());
    }
  }

  private int port;

  public DHCPTRIGGER_PORT_ALREADY_IN_USE(int port) {
    super(new String[]{"XYNA-09703", port + ""});
    setPort(port);
  }

  public DHCPTRIGGER_PORT_ALREADY_IN_USE(int port, Throwable cause) {
    super(new String[]{"XYNA-09703", port + ""}, cause);
    setPort(port);
  }

  protected DHCPTRIGGER_PORT_ALREADY_IN_USE(String[] args) {
    super(args);
  }

  protected DHCPTRIGGER_PORT_ALREADY_IN_USE(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setPort(int port) {
    this.port = port;
  }

  public int getPort() {
    return port;
  }

  public DHCPTRIGGER_PORT_ALREADY_IN_USE initCause(Throwable t) {
    return (DHCPTRIGGER_PORT_ALREADY_IN_USE) super.initCause(t);
  }


}
