/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.utils.exceptions.xmlstorage;

import com.gip.xyna.utils.exceptions.XynaException;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2010-06-02T10:09:58Z;
public class XSDNotFoundException extends XynaException {


  private String xsdFileName;

  public XSDNotFoundException(String xsdFileName) {
    super(new String[]{"XYNA-00020", xsdFileName + ""});
    setXsdFileName(xsdFileName);
  }

  public XSDNotFoundException(String xsdFileName, Throwable cause) {
    super(new String[]{"XYNA-00020", xsdFileName + ""}, cause);
    setXsdFileName(xsdFileName);
  }

  protected XSDNotFoundException(String[] args) {
    super(args);
  }

  protected XSDNotFoundException(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setXsdFileName(String xsdFileName) {
    this.xsdFileName = xsdFileName;
  }

  public String getXsdFileName() {
    return xsdFileName;
  }

  public XSDNotFoundException initCause(Throwable t) {
    return (XSDNotFoundException) super.initCause(t);
  }


}
