/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 GIP SmartMercial GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.utils.exceptions.utils.codegen;

import com.gip.xyna.utils.exceptions.XynaException;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2010-06-02T10:09:58Z;
public class InvalidParameterNameException extends XynaException {


  private String invalidParameter;

  public InvalidParameterNameException(String invalidParameter) {
    super(new String[]{"XYNA-00025", invalidParameter + ""});
    setInvalidParameter(invalidParameter);
  }

  public InvalidParameterNameException(String invalidParameter, Throwable cause) {
    super(new String[]{"XYNA-00025", invalidParameter + ""}, cause);
    setInvalidParameter(invalidParameter);
  }

  protected InvalidParameterNameException(String[] args) {
    super(args);
  }

  protected InvalidParameterNameException(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setInvalidParameter(String invalidParameter) {
    this.invalidParameter = invalidParameter;
  }

  public String getInvalidParameter() {
    return invalidParameter;
  }

  public InvalidParameterNameException initCause(Throwable t) {
    return (InvalidParameterNameException) super.initCause(t);
  }


}
