/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2023 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.utils.exceptions.utils.codegen;

import com.gip.xyna.utils.exceptions.XynaException;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2010-06-02T10:09:58Z;
public class InvalidClassNameException extends XynaException {


  private String fqClassName;

  public InvalidClassNameException(String fqClassName) {
    super(new String[]{"XYNA-00024", fqClassName + ""});
    setFqClassName(fqClassName);
  }

  public InvalidClassNameException(String fqClassName, Throwable cause) {
    super(new String[]{"XYNA-00024", fqClassName + ""}, cause);
    setFqClassName(fqClassName);
  }

  protected InvalidClassNameException(String[] args) {
    super(args);
  }

  protected InvalidClassNameException(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setFqClassName(String fqClassName) {
    this.fqClassName = fqClassName;
  }

  public String getFqClassName() {
    return fqClassName;
  }

  public InvalidClassNameException initCause(Throwable t) {
    return (InvalidClassNameException) super.initCause(t);
  }


}
