#!/bin/bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Copyright 2022 Xyna GmbH, Germany
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# description: Starts and stops TOKEN_PROVIDES_NAD

NAD_USER="TOKEN_NAD_USER"
NAD_DIR="TOKEN_INSTALL_PREFIX/NetworkAvailability"
VOLATILE_LOGGER="TOKEN_LOGGER";
LOG_FACILITY="TOKEN_LOG_FACILITY";


case "$1" in
  start)
    if [[ -e ${NAD_DIR}/networkAvailabilityDemon.sh ]] ; then
      echo -n "Starting Network-Availability-Demon as user '${NAD_USER}' "
      su - ${NAD_USER} -c "${NAD_DIR}/networkAvailabilityDemon.sh &"
    else 
      echo "No networkAvailabilityDemon.sh accessible in path ${NAD_DIR}"
      exit 5;
    fi;
    ;;
  stop)
    echo -n "Shutting down Network-Availability-Demon as user '${NAD_USER}' "
    kill $(cat ${NAD_DIR}/networkAvailabilityDemon.pid)
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  demon)
    while true; do
      if [[ -e ${NAD_DIR}/networkAvailabilityDemon.sh ]] ; then
        kill $(cat ${NAD_DIR}/networkAvailabilityDemon.pid)
        su - ${NAD_USER} -c "${NAD_DIR}/networkAvailabilityDemon.sh"
      else
        echo "No networkAvailabilityDemon.sh accessible in path ${NAD_DIR}" | 
          ${VOLATILE_LOGGER} -p "${LOG_FACILITY}.debug" &
        sleep 60; 
      fi
    done
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|demon}"
    echo
    exit 1
    ;;
esac
