#!/bin/bash
# ---------------------------------------------------
#  Copyright GIP AG 2015
#  (http://www.gip.com)
#
#  Hechtsheimer Str. 35-37
#  55131 Mainz
# ---------------------------------------------------
#  $Revision: 56658 $
#  $Date: 2009-11-26 11:39:17 +0100 (Do, 26 Nov 2009) $
# ---------------------------------------------------

### BEGIN INIT INFO
# Provides:          TOKEN_PROVIDES_NAD
# Default-Start:     
# Default-Stop:      0 1 
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
### END INIT INFO

NAD_USER="TOKEN_NAD_USER"
NAD_DIR="TOKEN_INSTALL_PREFIX/NetworkAvailability"
VOLATILE_LOGGER="TOKEN_LOGGER";
LOG_FACILITY="TOKEN_LOG_FACILITY";

. /etc/rc.status
rc_reset

case "$1" in
  start)
    if [[ -e ${NAD_DIR}/networkAvailabilityDemon.sh ]] ; then
      echo -n "Starting Network-Availability-Demon as user '${NAD_USER}' "
      su - ${NAD_USER} -c "${NAD_DIR}/networkAvailabilityDemon.sh &"
      rc_status -v
    else 
      echo "No networkAvailabilityDemon.sh accessible in path ${NAD_DIR}"
      exit 5;
    fi;
    ;;
  stop)
    echo -n "Shutting down Network-Availability-Demon as user '${NAD_USER}' "
    kill $(cat ${NAD_DIR}/networkAvailabilityDemon.pid)
    rc_status -v
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  demon)
    while true; do
      if [[ -e ${NAD_DIR}/networkAvailabilityDemon.sh ]] ; then
        kill $(cat ${NAD_DIR}/networkAvailabilityDemon.pid)
        su - ${NAD_USER} -c "${NAD_DIR}/networkAvailabilityDemon.sh"
      else
        echo "No networkAvailabilityDemon.sh accessible in path ${NAD_DIR}" | 
          ${VOLATILE_LOGGER} -p "${LOG_FACILITY}.debug" &
        sleep 60; 
      fi
    done
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|demon}"
    echo
    exit 1
    ;;
esac
rc_exit

