#!/bin/bash
# ---------------------------------------------------
#  Copyright GIP AG 2015
#  (http://www.gip.com)
#
#  Hechtsheimer Str. 35-37
#  55131 Mainz
# ---------------------------------------------------
#  $Revision: 56658 $
#  $Date: 2009-11-26 11:39:17 +0100 (Do, 26 Nov 2009) $
# ---------------------------------------------------

### BEGIN INIT INFO
# Provides:          TOKEN_PROVIDES_XYNA_FACTORY
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     $remote_fs $syslog $all
### END INIT INFO

XYNA_USER="TOKEN_XYNA_USER"
FACTORY_DIR="TOKEN_INSTALL_PREFIX/server"

test -x ${FACTORY_DIR} || { echo "${FACTORY_DIR} not installed";
  if [[ "$1" == "stop" ]]; then exit 0;
  else exit 5; fi; }

case "$1" in
  start)
    echo "Starting Xyna Factory as user '${XYNA_USER}' "
    ${FACTORY_DIR}/xynafactory.sh -q start
    ;;
  stop)
    echo "Shutting down Xyna Factory as user '${XYNA_USER}' "
    ${FACTORY_DIR}/xynafactory.sh -q stop
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    echo "Checking for service Xyna Factory as user '${XYNA_USER}' "
    ${FACTORY_DIR}/xynafactory.sh status
    ;;
  version)
    ${FACTORY_DIR}/xynafactory.sh version
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|version}"
    echo
    echo "Maybe you intended to run this command within the XynaFactory-CommandLine, like this?" 
    echo "  ${FACTORY_DIR}/xynafactory.sh $@"
    echo
    exit 1
    ;;
esac
