#!/bin/bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Copyright 2022 GIP SmartMercial GmbH, Germany
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

### BEGIN INIT INFO
# Provides:          TOKEN_PROVIDES_XYNA_FACTORY
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
### END INIT INFO

XYNA_USER="TOKEN_XYNA_USER"
FACTORY_DIR="TOKEN_INSTALL_PREFIX/server"

test -x ${FACTORY_DIR} || { echo "${FACTORY_DIR} not installed";
  if [[ "$1" == "stop" ]]; then exit 0;
  else exit 5; fi; }

. /etc/rc.status
rc_reset

case "$1" in
  start)
    echo -n "Starting Xyna Factory as user '${XYNA_USER}' "
    ${FACTORY_DIR}/xynafactory.sh -q start
    rc_status -v
    ;;
  stop)
    echo -n "Shutting down Xyna Factory as user '${XYNA_USER}' "
    ${FACTORY_DIR}/xynafactory.sh -q stop
    rc_status -v
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    echo -n "Checking for service Xyna Factory as user '${XYNA_USER}' "
    ${FACTORY_DIR}/xynafactory.sh status
    rc_status -v
    ;;
  version)
    ${FACTORY_DIR}/xynafactory.sh version
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|version}"
    echo
    echo "Maybe you intended to run this command within the XynaFactory-CommandLine, like this?" 
    echo "  ${FACTORY_DIR}/xynafactory.sh $@"
    echo
    exit 1
    ;;
esac
rc_exit

