/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.xact.trigger.dhcp;

import java.util.List;
import java.lang.NoSuchFieldException;
import java.util.concurrent.ConcurrentHashMap;
import java.lang.Class;
import com.gip.xyna.xact.exceptions.XACT_TriggerCouldNotBeStartedException;
import java.lang.reflect.Field;
import java.lang.IllegalArgumentException;
import com.gip.xyna.utils.exceptions.ExceptionStorage;
import java.util.concurrent.ConcurrentMap;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2026-01-08T16:25:29Z;
public class RADIUSTRIGGER_PORT_ALREADY_IN_USE extends XACT_TriggerCouldNotBeStartedException {

  private static ConcurrentMap<String, Field> fieldMap = new ConcurrentHashMap();
  static {
    {
      ExceptionStorage.loadFromResource("Exceptions.xml", RADIUSTRIGGER_PORT_ALREADY_IN_USE.class.getClassLoader());
    }
  }

  private int port;

  private RADIUSTRIGGER_PORT_ALREADY_IN_USE() {
    super(new String[] {"XYNA-09703", null});
  }

  public RADIUSTRIGGER_PORT_ALREADY_IN_USE(int port) {
    super(new String[]{"XYNA-09703", port + ""});
    setPort(port);
  }

  public RADIUSTRIGGER_PORT_ALREADY_IN_USE(int port, Throwable cause) {
    super(new String[]{"XYNA-09703", port + ""}, cause);
    setPort(port);
  }

  protected RADIUSTRIGGER_PORT_ALREADY_IN_USE(String[] args) {
    super(args);
  }

  protected RADIUSTRIGGER_PORT_ALREADY_IN_USE(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setPort(int port) {
    this.port = port;
  }

  public int getPort() {
    return port;
  }

  protected void refreshArgs() {
    super.refreshArgs();
    String[] args = getArgs();
    args[0] = port + "";
  }

  public RADIUSTRIGGER_PORT_ALREADY_IN_USE initCause(Throwable t) {
    return (RADIUSTRIGGER_PORT_ALREADY_IN_USE) super.initCause(t);
  }

  public static Field getField(String target_fieldname) {
    Field foundField = null;
    foundField = fieldMap.get(target_fieldname);
    if (foundField != null) {
      return foundField;
    }
    try {
      foundField = RADIUSTRIGGER_PORT_ALREADY_IN_USE.class.getDeclaredField(target_fieldname);
    } catch (NoSuchFieldException e) {
    }
    if (foundField == null) {
      return XACT_TriggerCouldNotBeStartedException.getField(target_fieldname);
    } else {
      foundField.setAccessible(true);
      fieldMap.put(target_fieldname, foundField);
      return foundField;
    }
  }



}
