/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package com.gip.xyna.xact.trigger.dhcp;

import com.gip.xyna.utils.exceptions.XynaException;
import java.util.List;
import java.lang.NoSuchFieldException;
import java.util.concurrent.ConcurrentHashMap;
import java.lang.Class;
import java.lang.reflect.Field;
import java.lang.IllegalArgumentException;
import com.gip.xyna.utils.exceptions.ExceptionStorage;
import java.util.concurrent.ConcurrentMap;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2026-01-08T16:25:29Z;
public class RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS extends XynaException {

  private static ConcurrentMap<String, Field> fieldMap = new ConcurrentHashMap();
  static {
    {
      ExceptionStorage.loadFromResource("Exceptions.xml", RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS.class.getClassLoader());
    }
  }

  private String parameterDescriptions;

  private RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS() {
    super(new String[] {"XYNA-09620", null});
  }

  public RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS(String parameterDescriptions) {
    super(new String[]{"XYNA-09620", parameterDescriptions + ""});
    setParameterDescriptions(parameterDescriptions);
  }

  public RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS(String parameterDescriptions, Throwable cause) {
    super(new String[]{"XYNA-09620", parameterDescriptions + ""}, cause);
    setParameterDescriptions(parameterDescriptions);
  }

  protected RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS(String[] args) {
    super(args);
  }

  protected RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS(String[] args, Throwable cause) {
    super(args, cause);
  }

  public void setParameterDescriptions(String parameterDescriptions) {
    this.parameterDescriptions = parameterDescriptions;
  }

  public String getParameterDescriptions() {
    return parameterDescriptions;
  }

  protected void refreshArgs() {
    String[] args = getArgs();
    args[0] = parameterDescriptions + "";
  }

  public RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS initCause(Throwable t) {
    return (RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS) super.initCause(t);
  }

  public static Field getField(String target_fieldname) {
    Field foundField = null;
    foundField = fieldMap.get(target_fieldname);
    if (foundField != null) {
      return foundField;
    }
    try {
      foundField = RADIUSTRIGGER_DHCP_INVALID_STARTPARAMETERS.class.getDeclaredField(target_fieldname);
    } catch (NoSuchFieldException e) {
    }
    if (foundField == null) {
      throw new IllegalArgumentException("Parameter 'target_fieldname' not found");
    } else {
      foundField.setAccessible(true);
      fieldMap.put(target_fieldname, foundField);
      return foundField;
    }
  }



}
