/*
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright 2022 Xyna GmbH, Germany
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
package ex.test;

import ex.test3.TestBaseException;
import java.util.List;

//DO NOT CHANGE
//GENERATED BY com.gip.xyna.utils.exceptions.utils.codegen.JavaClass 2010-08-20T11:50:48Z;
public class TestException5 extends TestBaseException {



  public TestException5() {
    super(new String[]{"XYNATEST2-00005"});
  }

  public TestException5(Throwable cause) {
    super(new String[]{"XYNATEST2-00005"}, cause);
  }

  protected TestException5(String[] args) {
    super(args);
  }

  protected TestException5(String[] args, Throwable cause) {
    super(args, cause);
  }

  public TestException5 initCause(Throwable t) {
    return (TestException5) super.initCause(t);
  }


}
