name: Check on pull-request

on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: run checkAppVersions.py
      run: |
        cd installation/build
        ./checkAppVersions.py

    - name: run checkServerVersion.sh
      run: |
        cd installation/build
        ./checkServerVersion.sh
